# repos:
# -   repo: git://github.com/pre-commit/pre-commit-hooks
#     sha: v1.2.3  # Use the ref you want to point at
#     hooks:
#     -   id: check-json
#     -   id: flake8
#     -   id: end-of-file-fixer
#     -   id: trailing-whitespace
#     -   id: name-tests-test
